#!/bin/bash

if [ ! $# -eq 2 ]
then
  echo "Usage: ./setup_apache [template container name] [path to website]"
  exit 1
fi

# Set up the website
pathtocontainer="/var/lib/lxc/""$1""/rootfs"
websitepath="$pathtocontainer""/var/www"

# TODO - I think this is right, but I'm not sure
# Specifically, I'm unsure if there's an additional file structure that we need
# I looked at the apache setup tutorial for like two seconds lmao
cp -r "$2" "$websitepath"

# Start apache?
# TODO
